//! Per-opcode integration tests driven by the SingleStepTests/65x02 corpus.

mod common;

use common::{TestCase, load_opcode_cases};
use nies_core::bus::BusLike;

pub struct FlatBus {
    pub mem: [u8; 0x10000],
    pub trace: Vec<(u16, u8, &'static str)>,
}

impl FlatBus {
    fn new() -> Self {
        FlatBus {
            mem: [0u8; 0x10000],
            trace: Vec::with_capacity(16),
        }
    }
}

impl BusLike for FlatBus {
    fn read(&mut self, addr: u16) -> u8 {
        let val = self.mem[addr as usize];
        self.trace.push((addr, val, "read"));
        val
    }
    fn write(&mut self, addr: u16, val: u8) {
        self.mem[addr as usize] = val;
        self.trace.push((addr, val, "write"));
    }
}

pub fn run_opcode_tests(opcode: u8) {
    let cases = load_opcode_cases(opcode);
    let mut failures = 0usize;
    let mut first_failure: Option<String> = None;

    for case in &cases {
        match run_single_case(case) {
            Ok(()) => {}
            Err(msg) => {
                failures += 1;
                if first_failure.is_none() {
                    first_failure = Some(format!("case '{}': {msg}", case.name));
                }
            }
        }
    }

    if failures > 0 {
        panic!(
            "opcode ${opcode:02X}: {failures}/{} cases failed.\nFirst failure: {}",
            cases.len(),
            first_failure.as_deref().unwrap_or("?")
        );
    }
}

fn run_single_case(case: &TestCase) -> Result<(), String> {
    let mut bus = FlatBus::new();
    for &(addr, val) in &case.initial.ram {
        bus.mem[addr as usize] = val;
    }
    let mut cpu = nies_core::cpu::Cpu::new();
    cpu.pc = case.initial.pc;
    cpu.sp = case.initial.s;
    cpu.a = case.initial.a;
    cpu.x = case.initial.x;
    cpu.y = case.initial.y;
    cpu.p = case.initial.p;

    cpu.step(&mut bus);

    if cpu.pc != case.r#final.pc {
        return Err(format!(
            "PC: expected {:04X}, got {:04X}",
            case.r#final.pc, cpu.pc
        ));
    }
    if cpu.sp != case.r#final.s {
        return Err(format!(
            "S: expected {:02X}, got {:02X}",
            case.r#final.s, cpu.sp
        ));
    }
    if cpu.a != case.r#final.a {
        return Err(format!(
            "A: expected {:02X}, got {:02X}",
            case.r#final.a, cpu.a
        ));
    }
    if cpu.x != case.r#final.x {
        return Err(format!(
            "X: expected {:02X}, got {:02X}",
            case.r#final.x, cpu.x
        ));
    }
    if cpu.y != case.r#final.y {
        return Err(format!(
            "Y: expected {:02X}, got {:02X}",
            case.r#final.y, cpu.y
        ));
    }
    if cpu.p != case.r#final.p {
        return Err(format!(
            "P: expected {:02X}, got {:02X}",
            case.r#final.p, cpu.p
        ));
    }
    for (addr, expected) in &case.r#final.ram {
        let got = bus.mem[*addr as usize];
        if got != *expected {
            return Err(format!(
                "ram[{addr:04X}]: expected {expected:02X}, got {got:02X}"
            ));
        }
    }
    if bus.trace.len() != case.cycles.len() {
        return Err(format!(
            "cycle count: expected {}, got {}",
            case.cycles.len(),
            bus.trace.len()
        ));
    }
    for (i, (expected, actual)) in case.cycles.iter().zip(bus.trace.iter()).enumerate() {
        if expected.0 != actual.0 || expected.1 != actual.1 || expected.2 != actual.2 {
            return Err(format!(
                "cycle {i}: expected ({:04X}, {:02X}, {}), got ({:04X}, {:02X}, {})",
                expected.0, expected.1, expected.2, actual.0, actual.1, actual.2
            ));
        }
    }
    Ok(())
}
// All 256 per-opcode SingleStepTests entries are generated by this
// `opcode_tests!` macro. Each invocation expands to:
//
//     #[test]
//     fn $name() { run_opcode_tests($opcode); }
//
// Plus a const block that asserts every opcode 0x00..=0xFF appears
// exactly once — so any future opcode getting accidentally dropped
// from this list is a compile error, not a silent gap in coverage.
//
// The naming convention is `opcode_<lowercase hex>_<mnemonic>_<mode>`,
// e.g. `opcode_a9_lda_imm`. Use `cargo test -p nies-core --test
// singlestep_tests opcode_` to run all 256 in parallel.

macro_rules! opcode_tests {
    ( $( $opcode:literal => $name:ident ),* $(,)? ) => {
        $(
            #[test]
            fn $name() {
                run_opcode_tests($opcode);
            }
        )*

        // Compile-time exhaustiveness check: every byte 0x00..=0xFF is
        // covered exactly once. Adding a new opcode means adding it
        // here too, or the build breaks.
        const _: () = {
            let mut covered = [0u8; 256];
            $(
                covered[$opcode as usize] += 1;
            )*
            let mut i = 0;
            while i < 256 {
                if covered[i] == 0 {
                    panic!("opcode_tests! macro is missing an entry for some opcode");
                }
                if covered[i] > 1 {
                    panic!("opcode_tests! macro has a duplicate entry for some opcode");
                }
                i += 1;
            }
        };
    };
}

opcode_tests! {
    0xA9 => opcode_a9_lda_imm,
    0xA5 => opcode_a5_lda_zp,
    0xB5 => opcode_b5_lda_zpx,
    0xAD => opcode_ad_lda_abs,
    0xBD => opcode_bd_lda_absx,
    0xB9 => opcode_b9_lda_absy,
    0xA1 => opcode_a1_lda_indx,
    0xB1 => opcode_b1_lda_indy,
    0xA2 => opcode_a2_ldx_imm,
    0xA6 => opcode_a6_ldx_zp,
    0xB6 => opcode_b6_ldx_zpy,
    0xAE => opcode_ae_ldx_abs,
    0xBE => opcode_be_ldx_absy,
    0xA0 => opcode_a0_ldy_imm,
    0xA4 => opcode_a4_ldy_zp,
    0xB4 => opcode_b4_ldy_zpx,
    0xAC => opcode_ac_ldy_abs,
    0xBC => opcode_bc_ldy_absx,
    0x85 => opcode_85_sta_zp,
    0x95 => opcode_95_sta_zpx,
    0x8D => opcode_8d_sta_abs,
    0x9D => opcode_9d_sta_absx,
    0x99 => opcode_99_sta_absy,
    0x81 => opcode_81_sta_indx,
    0x91 => opcode_91_sta_indy,
    0x86 => opcode_86_stx_zp,
    0x96 => opcode_96_stx_zpy,
    0x8E => opcode_8e_stx_abs,
    0x84 => opcode_84_sty_zp,
    0x94 => opcode_94_sty_zpx,
    0x8C => opcode_8c_sty_abs,
    0x29 => opcode_29_and_imm,
    0x25 => opcode_25_and_zp,
    0x35 => opcode_35_and_zpx,
    0x2D => opcode_2d_and_abs,
    0x3D => opcode_3d_and_absx,
    0x39 => opcode_39_and_absy,
    0x21 => opcode_21_and_indx,
    0x31 => opcode_31_and_indy,
    0x09 => opcode_09_ora_imm,
    0x05 => opcode_05_ora_zp,
    0x15 => opcode_15_ora_zpx,
    0x0D => opcode_0d_ora_abs,
    0x1D => opcode_1d_ora_absx,
    0x19 => opcode_19_ora_absy,
    0x01 => opcode_01_ora_indx,
    0x11 => opcode_11_ora_indy,
    0x49 => opcode_49_eor_imm,
    0x45 => opcode_45_eor_zp,
    0x55 => opcode_55_eor_zpx,
    0x4D => opcode_4d_eor_abs,
    0x5D => opcode_5d_eor_absx,
    0x59 => opcode_59_eor_absy,
    0x41 => opcode_41_eor_indx,
    0x51 => opcode_51_eor_indy,
    0x69 => opcode_69_adc_imm,
    0x65 => opcode_65_adc_zp,
    0x75 => opcode_75_adc_zpx,
    0x6D => opcode_6d_adc_abs,
    0x7D => opcode_7d_adc_absx,
    0x79 => opcode_79_adc_absy,
    0x61 => opcode_61_adc_indx,
    0x71 => opcode_71_adc_indy,
    0xE9 => opcode_e9_sbc_imm,
    0xE5 => opcode_e5_sbc_zp,
    0xF5 => opcode_f5_sbc_zpx,
    0xED => opcode_ed_sbc_abs,
    0xFD => opcode_fd_sbc_absx,
    0xF9 => opcode_f9_sbc_absy,
    0xE1 => opcode_e1_sbc_indx,
    0xF1 => opcode_f1_sbc_indy,
    0xC9 => opcode_c9_cmp_imm,
    0xC5 => opcode_c5_cmp_zp,
    0xD5 => opcode_d5_cmp_zpx,
    0xCD => opcode_cd_cmp_abs,
    0xDD => opcode_dd_cmp_absx,
    0xD9 => opcode_d9_cmp_absy,
    0xC1 => opcode_c1_cmp_indx,
    0xD1 => opcode_d1_cmp_indy,
    0xE0 => opcode_e0_cpx_imm,
    0xE4 => opcode_e4_cpx_zp,
    0xEC => opcode_ec_cpx_abs,
    0xC0 => opcode_c0_cpy_imm,
    0xC4 => opcode_c4_cpy_zp,
    0xCC => opcode_cc_cpy_abs,
    0x24 => opcode_24_bit_zp,
    0x2C => opcode_2c_bit_abs,
    0x0A => opcode_0a_asl_acc,
    0x06 => opcode_06_asl_zp,
    0x16 => opcode_16_asl_zpx,
    0x0E => opcode_0e_asl_abs,
    0x1E => opcode_1e_asl_absx,
    0x4A => opcode_4a_lsr_acc,
    0x46 => opcode_46_lsr_zp,
    0x56 => opcode_56_lsr_zpx,
    0x4E => opcode_4e_lsr_abs,
    0x5E => opcode_5e_lsr_absx,
    0x2A => opcode_2a_rol_acc,
    0x26 => opcode_26_rol_zp,
    0x36 => opcode_36_rol_zpx,
    0x2E => opcode_2e_rol_abs,
    0x3E => opcode_3e_rol_absx,
    0x6A => opcode_6a_ror_acc,
    0x66 => opcode_66_ror_zp,
    0x76 => opcode_76_ror_zpx,
    0x6E => opcode_6e_ror_abs,
    0x7E => opcode_7e_ror_absx,
    0xE6 => opcode_e6_inc_zp,
    0xF6 => opcode_f6_inc_zpx,
    0xEE => opcode_ee_inc_abs,
    0xFE => opcode_fe_inc_absx,
    0xC6 => opcode_c6_dec_zp,
    0xD6 => opcode_d6_dec_zpx,
    0xCE => opcode_ce_dec_abs,
    0xDE => opcode_de_dec_absx,
    0xE8 => opcode_e8_inx,
    0xC8 => opcode_c8_iny,
    0xCA => opcode_ca_dex,
    0x88 => opcode_88_dey,
    0x90 => opcode_90_bcc,
    0xB0 => opcode_b0_bcs,
    0xF0 => opcode_f0_beq,
    0xD0 => opcode_d0_bne,
    0x30 => opcode_30_bmi,
    0x10 => opcode_10_bpl,
    0x50 => opcode_50_bvc,
    0x70 => opcode_70_bvs,
    0x4C => opcode_4c_jmp_abs,
    0x6C => opcode_6c_jmp_ind,
    0x20 => opcode_20_jsr,
    0x60 => opcode_60_rts,
    0x48 => opcode_48_pha,
    0x08 => opcode_08_php,
    0x68 => opcode_68_pla,
    0x28 => opcode_28_plp,
    0x00 => opcode_00_brk,
    0x40 => opcode_40_rti,
    0xAA => opcode_aa_tax,
    0xA8 => opcode_a8_tay,
    0x8A => opcode_8a_txa,
    0x98 => opcode_98_tya,
    0xBA => opcode_ba_tsx,
    0x9A => opcode_9a_txs,
    0x18 => opcode_18_clc,
    0x38 => opcode_38_sec,
    0x58 => opcode_58_cli,
    0x78 => opcode_78_sei,
    0xB8 => opcode_b8_clv,
    0xD8 => opcode_d8_cld,
    0xF8 => opcode_f8_sed,
    0xEA => opcode_ea_nop,
    0x1A => opcode_1a_nop_imp,
    0x3A => opcode_3a_nop_imp,
    0x5A => opcode_5a_nop_imp,
    0x7A => opcode_7a_nop_imp,
    0xDA => opcode_da_nop_imp,
    0xFA => opcode_fa_nop_imp,
    0x80 => opcode_80_nop_imm,
    0x82 => opcode_82_nop_imm,
    0x89 => opcode_89_nop_imm,
    0xC2 => opcode_c2_nop_imm,
    0xE2 => opcode_e2_nop_imm,
    0x04 => opcode_04_nop_zp,
    0x44 => opcode_44_nop_zp,
    0x64 => opcode_64_nop_zp,
    0x14 => opcode_14_nop_zpx,
    0x34 => opcode_34_nop_zpx,
    0x54 => opcode_54_nop_zpx,
    0x74 => opcode_74_nop_zpx,
    0xD4 => opcode_d4_nop_zpx,
    0xF4 => opcode_f4_nop_zpx,
    0x0C => opcode_0c_nop_abs,
    0x1C => opcode_1c_nop_absx,
    0x3C => opcode_3c_nop_absx,
    0x5C => opcode_5c_nop_absx,
    0x7C => opcode_7c_nop_absx,
    0xDC => opcode_dc_nop_absx,
    0xFC => opcode_fc_nop_absx,
    0xA3 => opcode_a3_lax_indx,
    0xA7 => opcode_a7_lax_zp,
    0xAF => opcode_af_lax_abs,
    0xB3 => opcode_b3_lax_indy,
    0xB7 => opcode_b7_lax_zpy,
    0xBF => opcode_bf_lax_absy,
    0x83 => opcode_83_sax_indx,
    0x87 => opcode_87_sax_zp,
    0x8F => opcode_8f_sax_abs,
    0x97 => opcode_97_sax_zpy,
    0xC3 => opcode_c3_dcp_indx,
    0xC7 => opcode_c7_dcp_zp,
    0xCF => opcode_cf_dcp_abs,
    0xD3 => opcode_d3_dcp_indy,
    0xD7 => opcode_d7_dcp_zpx,
    0xDB => opcode_db_dcp_absy,
    0xDF => opcode_df_dcp_absx,
    0xE3 => opcode_e3_isc_indx,
    0xE7 => opcode_e7_isc_zp,
    0xEF => opcode_ef_isc_abs,
    0xF3 => opcode_f3_isc_indy,
    0xF7 => opcode_f7_isc_zpx,
    0xFB => opcode_fb_isc_absy,
    0xFF => opcode_ff_isc_absx,
    0x03 => opcode_03_slo_indx,
    0x07 => opcode_07_slo_zp,
    0x0F => opcode_0f_slo_abs,
    0x13 => opcode_13_slo_indy,
    0x17 => opcode_17_slo_zpx,
    0x1B => opcode_1b_slo_absy,
    0x1F => opcode_1f_slo_absx,
    0x23 => opcode_23_rla_indx,
    0x27 => opcode_27_rla_zp,
    0x2F => opcode_2f_rla_abs,
    0x33 => opcode_33_rla_indy,
    0x37 => opcode_37_rla_zpx,
    0x3B => opcode_3b_rla_absy,
    0x3F => opcode_3f_rla_absx,
    0x43 => opcode_43_sre_indx,
    0x47 => opcode_47_sre_zp,
    0x4F => opcode_4f_sre_abs,
    0x53 => opcode_53_sre_indy,
    0x57 => opcode_57_sre_zpx,
    0x5B => opcode_5b_sre_absy,
    0x5F => opcode_5f_sre_absx,
    0x63 => opcode_63_rra_indx,
    0x67 => opcode_67_rra_zp,
    0x6F => opcode_6f_rra_abs,
    0x73 => opcode_73_rra_indy,
    0x77 => opcode_77_rra_zpx,
    0x7B => opcode_7b_rra_absy,
    0x7F => opcode_7f_rra_absx,
    0x0B => opcode_0b_anc_imm,
    0x2B => opcode_2b_anc_imm,
    0x4B => opcode_4b_alr_imm,
    0x6B => opcode_6b_arr_imm,
    0xCB => opcode_cb_axs_imm,
    0xEB => opcode_eb_sbc_imm,
    0x9C => opcode_9c_shy_absx,
    0x9E => opcode_9e_shx_absy,
    0x93 => opcode_93_sha_indy,
    0x9F => opcode_9f_sha_absy,
    0x9B => opcode_9b_tas_absy,
    0x8B => opcode_8b_xaa_imm,
    0xAB => opcode_ab_lxa_imm,
    0x02 => opcode_02_jam,
    0x12 => opcode_12_jam,
    0x22 => opcode_22_jam,
    0x32 => opcode_32_jam,
    0x42 => opcode_42_jam,
    0x52 => opcode_52_jam,
    0x62 => opcode_62_jam,
    0x72 => opcode_72_jam,
    0x92 => opcode_92_jam,
    0xB2 => opcode_b2_jam,
    0xD2 => opcode_d2_jam,
    0xF2 => opcode_f2_jam,
    0xBB => opcode_bb_las_absy,
}

// Note: an earlier revision of this file had a single
// `all_256_opcodes_pass` test that looped over every opcode
// sequentially. It was removed because:
//
//   - Cargo's test runner already parallelizes the 256 per-opcode
//     `#[test] fn opcode_NN_*()` entries above across CPU cores.
//     A single sweep test ran them serially in one thread, taking
//     ~25 s in debug vs ~5-10 s aggregate when the per-opcode
//     tests run in parallel.
//   - "All opcodes pass" is exactly what `cargo test --test
//     singlestep_tests opcode_` already produces, with naming
//     and parallelism for free.
//   - The CI gate is `cargo test`, which runs every `#[test]`
//     including all 256 per-opcode entries; no consolidated test
//     was adding coverage.
